config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :posts
  resources :users

  get 'dashboard' => 'users#dashboard'

  root to: 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# application_record model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

# post model
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  scope :published, -> { where.not(published_date: nil).where('published_date <= ?', Time.now) }

  def published?
    published_date.present? && published_date <= Time.now
  end

end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  enum role: {
    author: 0,
    admin: 2
  }

  def acts_as_admin?
    admin?
  end

  def acts_as_author?
    author? || admin?
  end

  def to_s
    name
  end

  def name
    [first_name, last_name].join(' ')
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index; end

  private

  def user_not_authorized
    flash.now[:error] = "You are not authorized to perform this action."

    redirect_to(request.referer || root_path)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = AirshipBlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# posts controller
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  after_action :verify_authorized, except: [:index, :dashboard, :execute]
  after_action :verify_policy_scoped, only: :index

  # GET /posts
  # GET /posts.json
  def index
    @posts = policy_scope Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(policy(Post).permitted_attributes)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  after_action :verify_authorized, except: [:index, :dashboard, :execute]
  after_action :verify_policy_scoped, only: :index

  def index
    @users = policy_scope User.all
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to redirect_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    if current_user
      @user = current_user
      render 'edit'
    else
      redirect_to root_path
    end
  end

  private

  def redirect_path
    if current_user.admin?
      users_path
    else
      dashboard_path
    end
  end

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(policy(User).permitted_attributes)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# posts helper
module PostsHelper
end

app/views/layouts/_login_links.html.haml
%h3
  - if user_signed_in?
    = link_to('Logout', destroy_user_session_path, method: :delete)
  - else
    = link_to('Login', new_user_session_path)

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-light.bg-light.navbar-expand-md
  = link_to image_tag('https://teamairship.com/wp-content/uploads/2016/07/airship-logo.svg', width: "35"), "/", class: "navbar-brand"

  %button.navbar-toggler{"aria-controls" => "navbar-toggle-content", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar-toggle-content", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#navbar-toggle-content.justify-content-end
    %ul.navbar-nav
      .dropdown-divider
      %li.nav-item
        = link_to posts_path, class: "nav-link" do
          Posts
      - if current_user
        .dropdown-divider
        %li.nav-item
          = link_to(dashboard_path, class: "nav-link") do
            Dashboard
        .dropdown-divider
        %li.nav-item
          = link_to(destroy_user_session_path, class: "nav-link", method: :delete) do
            Logout

      - else
        .dropdown-divider
        %li.nav-item
          = link_to(new_user_session_path, class: "nav-link") do
            Login

app/views/layouts/_notifications.html.haml
%center
  %p#notice= notice

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AirshipBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/nav'
    .container
      .row
        .col-md-12
          = render 'layouts/notifications'
          = yield

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title, class: "form-control"
  .field
    = form.label :content
    = form.text_area :content, class: "form-control"
  .field
    = form.label :published_date
    = form.text_field :published_date, placeholder: "2020-01-01", class: "form-control"

  .actions.mt-3
    = form.submit "Submit", class: "btn btn-primary"

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%center
  %h2.mb-3 Welcome to the Airship Blog!

%table.table
  %thead
    %tr
      %th Title
      %th Content
      %th author
      %th{:colspan => "2"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.title, post
        %td= post.content
        %td= post.user
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path, class: "btn btn-outline-primary"

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @post.title
%p
  %strong Content:
  = @post.content
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :email
    = form.text_field :email, class: "form-control"
  .field
    = form.label :first_name
    = form.text_field :first_name, class: "form-control"
  .field
    = form.label :last_name
    = form.text_field :last_name, class: "form-control"

  - if current_user.admin?
    .field
      = form.label :role
      = form.select :role, options_for_select(User.roles.keys, selected: user.role), {}, class: "form-control"

  .actions.mt-5
    = form.submit "Submit", class: "btn btn-primary"

app/views/users/edit.html.haml
%h1 Editing User

%hr

= render 'form', user: @user

= link_to 'Back', users_path

app/views/users/index.html.haml
%h2.mb-3 Users

%table.table
  %thead
    %th Email
    %th First Name
    %th Last Name
    %th Role
    %th{colspan: 3}

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name
        %td= user.role
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }